Task added
insidious163/tasks pull request #1
Opened 2023-06-03 17:23 UTC by insidious163

2023-06-03 18:39 UTC, dashawebb requested changes

2023-06-03 18:39 UTC, dashawebb commented on src/task/Task.js
> +const DateTimePicker = ({title, setFunction}) => {
В этом файле предлагаю каждый компонент вынести в свой отдельный файл

2023-06-03 18:39 UTC, dashawebb commented on src/task/Task.js
> +const DateTimePicker = ({title, setFunction}) => {
```
например, что-то такое:
src__
    |__components__
                  |__Task__
                          |__Task.js
                          |__Task.css                                                     
                  |__TaskName
                          |__TaskName.js
                          |__TaskName.css                                                     
                  |__TaskDescription
                          |__TaskDescription.js
                          |__TaskDescription.css 
    |__ui__
          |__DropdownPicker
                          |__DropdownPicker.js
                          |__DropdownPicker.css                                                     
          |__TextPicker____
                          |__TextPicker.js
                          |__TextPicker.css                                                     

```

2023-06-04 01:47 UTC, Muslik requested changes
Давай по новой

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/Task.js
> +export default Task;
Дефолтные экспорты зло в 99% случаях: https://t.me/why_not_export_default

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/Task.js
> +export default Task;
На будущее: В каждом проекте должен быть [prettier](https://prettier.io/),
а также [eslint](https://eslint.org/).

Один линтер, другой - форматтер. Это де факто сейчас стандарт

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/TaskDescription/TaskDescription.js
> +import TextPicker from "../../../ui/TextPicker/TextPicker";
https://stackoverflow.com/questions/68842451/how-to-use-absolute-paths-instead-of-relative-paths-in-react-or-next-js

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/TaskDescription/TaskDescription.js
> +import React from "react";
Для последних версий React, этот импорт уже не нужен

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/TaskDescription/TaskDescription.js
> +        <div className="Description">
Для классов минимальное что ты используешь - это css modules. То есть у тебя не один файл на весь проект где ты используешь стили, а у каждого компонента - свой файл стилей.

Create React App требует чтобы файл назывался Имя.module.css

И работать будет так. У тебя есть компонент и рядом стили:

TaskDescription.jsx
TaskDescription.module.css

```javascript
// TaskDescription.module.css
.description {
  // Some Styles
}

// TaskDescription.jsx
import styles from './TaskDescription.module.css';

// Теперь styles просто объект

const TaskDescription = () => {

  return ( <div className={styles.description}>Hello world</div>)
}

```

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/Task.js
> +import React, {useState} from "react";
Для инициализации чего то более современного CRA (create react app) уже все, он устарел.
Я бы использовал vite в качестве сборщика. Ну это так - на будущее

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/TaskExecutor/TaskExecutor.js
> +    const executors = [
Статичные вещи не нужно держать внутри компонента. Они будут пересоздаваться каждый раз при ререндере

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/TaskTiming/TaskTiming.js
> +                    type="radio"
У семейства radio должен быть аттрибут name

2023-06-04 01:47 UTC, Muslik commented on src/ui/DateTimePicker/DateTimePicker.js
> +const DateTimePicker = ({title, initValue, setFunction}) => {
1) Не называем переменные с описанием его типа. (setFunction, startInt, endString)
2) лучше не использовать сокращения (пишем полностью - initialValue) Но в данном случае это должно стать просто value
3) Так как это input, это должен быть не title, а label

2023-06-04 01:47 UTC, Muslik commented on src/ui/DateTimePicker/DateTimePicker.js
> +        setSelectedDateTime(event.target.value);
Сейчас по факту у тебя есть два стейта и ты их пытаешься синхронизировать. Это всегда плохо.

Поэтому ты убираешь стейт из DateTimePicker и прокидываешь в него value. То есть он становится тупым. Сам ничего не решает. За него все решает родитель и стейт лежит там

```<DatePicker value={} onChange={} />```

2023-06-04 01:47 UTC, Muslik commented on src/ui/DateTimePicker/DateTimePicker.js
> +        setSelectedDateTime(event.target.value);
По поводу именования пропсов. На первое время думаю стоит придерживаться такого

Обычно для именования функций обработчиков используется префикс on(change/select/click)

А в месте где хранится функция-обработчик префикс handle

```javascript
const MyInput = () => {

  const handleChangeDate = () => {}
  
  const handleSubmit = () => {}
  
  const handleClickReload = () => {}

  return <>
    <input onChange={handleChangeDate} name="date" />
    <button onClick={handleClickReload}>Reload</button>
    <button onClick={handleSubmit}> Submit </button>
  </>
}
```

2023-06-04 01:47 UTC, Muslik commented on src/ui/DateTimePicker/DateTimePicker.js
> +    const handleDateTimeChange = (event) => {
Деструктуризируем сразу по месту: `({ target: { value }}) => {...}`

2023-06-04 01:47 UTC, Muslik commented on src/ui/DropdownPicker/DropdownPicker.js
> +        setFunction(values.find((el) => el.id === event.target.value));
В стейте должен лежать только value. Не нужно класть туда целый объект. Если тебе нужен все же целый объект, доставай его ниже

```javascript
const data = [{ id: 1, name: 'Trahych' }, { id: 2, name: 'Darya' }];

const Component = () => {
  const [selectedUserId, setSelectedUserId] = useState(null);
  
  const selectedUser = selectedUser.find(({ id }) => id === selectedUserId);
  
  return ...
}
```

2023-06-04 01:47 UTC, Muslik commented on src/ui/DropdownPicker/DropdownPicker.js
> +                {values.map((value) => (
Обычно деструктуризируют: 
```javascript
values.map(({ id, name }) => ...)
```

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/Task.js
> +
Стандартный отступ в js - два пробела

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/Task.js
> +    const [task, setTask] = useState('');
У тебя тип данных там не строка а объект

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/Task.js
> +            <TaskName setValueInTask={setValueInTask}/>
В качестве учебного ок, но никто обычно не разделяет форму из нескольких полей на кучу компонентов.

Это все будет один компонент

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/Task.js
> +            <TaskDescription setValueInTask={setValueInTask}/>
Я бы сделал замыкание: 

```javascript
const Task = () => {
  const handleChangeField = (key) => (value) => {
  
  }
  
  return (
    <TaskName onChange={handleChangeField('name')} />
    <TaskDescription onChange={handleChangeField('description'} />
  )
}
```

То есть теперь мы не размазываем логику по всем компонентам чтобы они знали что они меняют и где.
Они будут оставаться тупыми. Просто реагируют на пропсы которые ты им отдаешь.

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/Task.js
> +            <TaskExecutor setValueInTask={setValueInTask}/>
executor-ов лучше достать оттуда. И будут передаваться отсюда

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/Task.js
> +            <TaskName setValueInTask={setValueInTask}/>
Потому что сейчас у тебя сделан компонент ради компонента. И можно для пары компонентов это упростить.

```javascript
const executors = [
    {name: 'Me', id: '1'},
    {name: 'Nikiana', id: '2'},
    {name: 'Webb', id: '3'},
];

const Task = () => {
  const handleChangeField = (key) => (value) => {
    ...
  }
  
  return (
    <div className={styles.task}>
        <div className="Name">
          <TextPicker title="Name" onChange={handleChangeField('name')} />
        </div>
        <div className="Executor">
            <DropdownPicker title="Executor" values={executors} onChange={handleChangeField('executor')} />
        </div>
    </div> 
  )

}
```

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/TaskTiming/TaskTiming.js
> +        setSelectedOption(event.target.value);
Опять синхронизируем два стейта

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/TaskTiming/TaskTiming.js
> +    const [deadline, setDeadline] = useState('');
Вместо того чтобы хранить 3 переменные, я бы сделал 1.

Назвать ее deadline. И у нее есть два варианта - либо конечная дата либо от и до

То есть либо: `{ from: null, to: '20.06.2023' }` либо `{ from: '13.06.2023', to: '20.06.2023' }`

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/TaskTiming/TaskTiming.js
> +            setValueInTask("deadline", deadline);
Из за того что у тебя три разных стейта тебе их постоянно надо синхронизировать, что то обнулять, что то устанавливать

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/TaskTiming/TaskTiming.js
> +    const [deadline, setDeadline] = useState('');
И будет красиво:

```javascript
const TaskTiming = ({ from, to, onChange }) => {
  const handleChangeDeadlineType = ({ target: { value }}) => {
    setSelectedOption(value);
    // Мы сбрасываем весь deadline при переключении опции
    onChange({ from: null, to: null });
  }

  // функция выполняет только установку данных. Она не занимается разбором кто это и что это. (как в твоем случае через if).
  // Вообще в принципе если в функции handleChange появляется if, иногда лучше разделить их на две отдельные 
  const handleChangeDeadline = (key) => (value) => {
    onChange({ [key]: value })
  }
  
  // Опять же если мы достанем компонент из промежуточного станет только лучше, не нужно будет прокидывать кучу пропсов.
  
  return (
    <>
     ...
    {selectedOption === 'deadline' && (
        <div className="Deadline">
          <DateTimePicker title="Deadline" value={to} setFunction={handleChangeDeadline('to')}/>
        </div>
    )}
    {selectedOption === "startAndFinish" && (
        <div className="StartAndFinish">
          <DateTimePicker title="Start" value={from} onChange={handleChangeDeadline('from')}/>
          <DateTimePicker title="Finish" value={to} setFunction={handleChangeDeadline('to')}/>
        </div>
    )}
    </>
  );
}
```

2023-06-04 01:47 UTC, Muslik commented on src/components/Task/TaskTiming/TaskTiming.js
> +            <dev>
*div

2023-06-04 01:47 UTC, Muslik commented on src/index.js
> +import Task from "./components/Task/Task";
Обычно в корне src есть Файл App.js И уже в него подключается Task. Потому что мало ли, тебе понадобится сделать несколько страниц или добавить общую стилизацию для приложения. Это все нужно будет делать не тут.

2023-06-04 01:47 UTC, Muslik commented on src/ui/DateTimePicker/DateTimePicker.js
> +            <h2>{title}</h2>
Лучше это превратить в label. Чтобы по клику на него выставлялся фокус в инпут.
Внутри тупого компонета с инпутом обычно не бывает пропсов title. Он либо будет где то выше, либо это label как у тебя тут

2023-06-04 01:47 UTC, Muslik commented on src/ui/DropdownPicker/DropdownPicker.js
> +const DropdownPicker = ({title, values, setFunction}) => {
better rename: values -> options.

2023-06-04 01:47 UTC, Muslik commented on src/ui/DropdownPicker/DropdownPicker.js
> +        setSelectedOption(event.target.value);
Опять же синхронизируем стейт, что плохо

2023-06-04 01:47 UTC, Muslik commented on src/ui/DropdownPicker/DropdownPicker.js
> +            <h2>{title}</h2>
Опять же это - label

2023-06-04 01:52 UTC, Muslik commented on src/components/Task/Task.js
> +export default Task;
Если в файле react компонент, расширение у файла - jsx

2023-06-07 23:06 UTC, closed without merging