Tasks added
insidious163/tasks pull request #2
Opened 2023-06-07 23:13 UTC by insidious163

2023-06-08 09:32 UTC, dashawebb requested changes

2023-06-08 09:32 UTC, dashawebb commented on src/components/Task/Task.module.css
> +.task {
можно давать менее дескриптивные имена стилям. Мы как правило класс родителя просто называем .root. Если у тебя подключены css-модули, имена классов не будут пересекаться.

2023-06-08 09:32 UTC, dashawebb commented on src/App.css
> +
все классы кроме root можно удалить, чтобы не мешались

2023-06-08 09:32 UTC, dashawebb commented on src/components/Task/Task.jsx
> +  const [task, setTask] = useState("");
остается прошлый коммент про тип. У тебя в task будет лежать объект, тогда давай инициализируем его `null`ом, а не пустой строкой

2023-06-08 09:32 UTC, dashawebb commented on src/components/Task/TaskTiming/TaskTiming.jsx
> +      <div>
этот div можно убрать

2023-06-08 09:32 UTC, dashawebb commented on src/components/Task/Task.jsx
> +      <TaskName setValueInTask={setValueInTask} />
имена хендлеров. Внутрь пробрасываем handleActionName (handleClick, handleSelected, handleChange), в самом компоненте при совершении действия onActionName (onClick etc...). 
Идея в том, что у тебя компонент глупый и даже не знает, что на высшем уровне от совершения действия произойдет – он знает только то, что ему надо вызвать обработчик действия Click.

2023-06-08 09:32 UTC, dashawebb commented on src/components/Task/TaskTiming/TaskTiming.jsx
> +    setSelectedOption(event.target.value);
деструктуризация event

2023-06-08 09:32 UTC, dashawebb commented on src/components/Task/Task.jsx
> +  const [task, setTask] = useState("");
либо давай учтем коммент Джаба и не будем хранить объект

2023-06-09 18:46 UTC, insidious163 commented on src/components/Task/Task.module.css
> +.task {
fixed

2023-06-09 18:47 UTC, insidious163 commented on src/components/Task/Task.jsx
> +  const [task, setTask] = useState("");
Не понял, как не хранить объект. По умолчанию скормил правильный json

2023-06-15 22:19 UTC, merged